#spring:
#  datasource:
#    url: jdbc:h2:mem:erpdb
#    username: erpdev
#    password: password123
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#
##
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_java
    username: abir1
    password: Abir@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
