spring:
  datasource:
    url: jdbc:h2:mem:erpdb
    username: erpdev
    password: password123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop



